//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 9/9/2014 1:47:50 PM
namespace CDM_SearchEngine.mdmpartnercustomer
{
    
    /// <summary>
    /// There are no comments for MDMPartnerCustomerEntities in the schema.
    /// </summary>
    public partial class MDMPartnerCustomerEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new MDMPartnerCustomerEntities object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MDMPartnerCustomerEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "MDMPartnerCustomerModel", "CDM_SearchEngine.mdmpartnercustomer");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("CDM_SearchEngine.mdmpartnercustomer", global::System.StringComparison.Ordinal))
            {
                return string.Concat("MDMPartnerCustomerModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for vw_Partner_Hierarchy_Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<vw_Partner_Hierarchy_Customer> vw_Partner_Hierarchy_Customer
        {
            get
            {
                if ((this._vw_Partner_Hierarchy_Customer == null))
                {
                    this._vw_Partner_Hierarchy_Customer = base.CreateQuery<vw_Partner_Hierarchy_Customer>("vw_Partner_Hierarchy_Customer");
                }
                return this._vw_Partner_Hierarchy_Customer;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<vw_Partner_Hierarchy_Customer> _vw_Partner_Hierarchy_Customer;
        /// <summary>
        /// There are no comments for vw_Partner_Hierarchy_Customer in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddTovw_Partner_Hierarchy_Customer(vw_Partner_Hierarchy_Customer vw_Partner_Hierarchy_Customer)
        {
            base.AddObject("vw_Partner_Hierarchy_Customer", vw_Partner_Hierarchy_Customer);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private const string ModelPart0 = "<edmx:Edmx Version=\"1.0\" xmlns:edmx=\"http://schemas.microsoft.com/ado/2007/06/edm" +
                "x\"><edmx:DataServices m:DataServiceVersion=\"1.0\" m:MaxDataServiceVersion=\"3.0\" x" +
                "mlns:m=\"http://schemas.microsoft.com/ado/2007/08/dataservices/metadata\"><Schema " +
                "Namespace=\"MDMPartnerCustomerModel\" xmlns=\"http://schemas.microsoft.com/ado/2008" +
                "/09/edm\"><EntityType Name=\"vw_Partner_Hierarchy_Customer\"><Key><PropertyRef Name" +
                "=\"Country_OrgID\" /><PropertyRef Name=\"Global_OrgID\" /><PropertyRef Name=\"Site_Or" +
                "gID\" /></Key><Property Name=\"Global_OrgID\" Type=\"Edm.String\" Nullable=\"false\" Ma" +
                "xLength=\"40\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Global_CustID\"" +
                " Type=\"Edm.Decimal\" Precision=\"38\" Scale=\"0\" /><Property Name=\"Country_OrgID\" Ty" +
                "pe=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\" FixedLength=\"false\" Unicode=\"tru" +
                "e\" /><Property Name=\"Country_CustID\" Type=\"Edm.Decimal\" Precision=\"38\" Scale=\"0\"" +
                " /><Property Name=\"Site_OrgID\" Type=\"Edm.String\" Nullable=\"false\" MaxLength=\"40\"" +
                " FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Site_CustID\" Type=\"Edm.Dec" +
                "imal\" Precision=\"38\" Scale=\"0\" /><Property Name=\"Global_Org_Name\" Type=\"Edm.Stri" +
                "ng\" MaxLength=\"90\" FixedLength=\"false\" Unicode=\"true\" /><Property Name=\"Country_" +
                "Org_Name\" Type=\"Edm.String\" MaxLength=\"90\" FixedLength=\"false\" Unicode=\"true\" />" +
                "<Property Name=\"Site_OrgName\" Type=\"Edm.String\" MaxLength=\"90\" FixedLength=\"fals" +
                "e\" Unicode=\"true\" /></EntityType><EntityContainer Name=\"MDMPartnerCustomerEntiti" +
                "es\" m:IsDefaultEntityContainer=\"true\" p6:LazyLoadingEnabled=\"true\" xmlns:p6=\"htt" +
                "p://schemas.microsoft.com/ado/2009/02/edm/annotation\"><EntitySet Name=\"vw_Partne" +
                "r_Hierarchy_Customer\" EntityType=\"MDMPartnerCustomerModel.vw_Partner_Hierarchy_C" +
                "ustomer\" /></EntityContainer></Schema></edmx:DataServices></edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static string GetConcatenatedEdmxString()
            {
                return string.Concat(ModelPart0);
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            public static global::Microsoft.Data.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::Microsoft.Data.Edm.IEdmModel LoadModelFromString()
            {
                string edmxToParse = GetConcatenatedEdmxString();
                global::System.Xml.XmlReader reader = CreateXmlReader(edmxToParse);
                try
                {
                    return global::Microsoft.Data.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
    /// <summary>
    /// There are no comments for MDMPartnerCustomerModel.vw_Partner_Hierarchy_Customer in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Country_OrgID
    /// Global_OrgID
    /// Site_OrgID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("vw_Partner_Hierarchy_Customer")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Country_OrgID", "Global_OrgID", "Site_OrgID")]
    public partial class vw_Partner_Hierarchy_Customer : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new vw_Partner_Hierarchy_Customer object.
        /// </summary>
        /// <param name="global_OrgID">Initial value of Global_OrgID.</param>
        /// <param name="country_OrgID">Initial value of Country_OrgID.</param>
        /// <param name="site_OrgID">Initial value of Site_OrgID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static vw_Partner_Hierarchy_Customer Createvw_Partner_Hierarchy_Customer(string global_OrgID, string country_OrgID, string site_OrgID)
        {
            vw_Partner_Hierarchy_Customer vw_Partner_Hierarchy_Customer = new vw_Partner_Hierarchy_Customer();
            vw_Partner_Hierarchy_Customer.Global_OrgID = global_OrgID;
            vw_Partner_Hierarchy_Customer.Country_OrgID = country_OrgID;
            vw_Partner_Hierarchy_Customer.Site_OrgID = site_OrgID;
            return vw_Partner_Hierarchy_Customer;
        }
        /// <summary>
        /// There are no comments for Property Global_OrgID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Global_OrgID
        {
            get
            {
                return this._Global_OrgID;
            }
            set
            {
                this.OnGlobal_OrgIDChanging(value);
                this._Global_OrgID = value;
                this.OnGlobal_OrgIDChanged();
                this.OnPropertyChanged("Global_OrgID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Global_OrgID;
        partial void OnGlobal_OrgIDChanging(string value);
        partial void OnGlobal_OrgIDChanged();
        /// <summary>
        /// There are no comments for Property Global_CustID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Global_CustID
        {
            get
            {
                return this._Global_CustID;
            }
            set
            {
                this.OnGlobal_CustIDChanging(value);
                this._Global_CustID = value;
                this.OnGlobal_CustIDChanged();
                this.OnPropertyChanged("Global_CustID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Global_CustID;
        partial void OnGlobal_CustIDChanging(global::System.Nullable<decimal> value);
        partial void OnGlobal_CustIDChanged();
        /// <summary>
        /// There are no comments for Property Country_OrgID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country_OrgID
        {
            get
            {
                return this._Country_OrgID;
            }
            set
            {
                this.OnCountry_OrgIDChanging(value);
                this._Country_OrgID = value;
                this.OnCountry_OrgIDChanged();
                this.OnPropertyChanged("Country_OrgID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country_OrgID;
        partial void OnCountry_OrgIDChanging(string value);
        partial void OnCountry_OrgIDChanged();
        /// <summary>
        /// There are no comments for Property Country_CustID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Country_CustID
        {
            get
            {
                return this._Country_CustID;
            }
            set
            {
                this.OnCountry_CustIDChanging(value);
                this._Country_CustID = value;
                this.OnCountry_CustIDChanged();
                this.OnPropertyChanged("Country_CustID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Country_CustID;
        partial void OnCountry_CustIDChanging(global::System.Nullable<decimal> value);
        partial void OnCountry_CustIDChanged();
        /// <summary>
        /// There are no comments for Property Site_OrgID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Site_OrgID
        {
            get
            {
                return this._Site_OrgID;
            }
            set
            {
                this.OnSite_OrgIDChanging(value);
                this._Site_OrgID = value;
                this.OnSite_OrgIDChanged();
                this.OnPropertyChanged("Site_OrgID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Site_OrgID;
        partial void OnSite_OrgIDChanging(string value);
        partial void OnSite_OrgIDChanged();
        /// <summary>
        /// There are no comments for Property Site_CustID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<decimal> Site_CustID
        {
            get
            {
                return this._Site_CustID;
            }
            set
            {
                this.OnSite_CustIDChanging(value);
                this._Site_CustID = value;
                this.OnSite_CustIDChanged();
                this.OnPropertyChanged("Site_CustID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<decimal> _Site_CustID;
        partial void OnSite_CustIDChanging(global::System.Nullable<decimal> value);
        partial void OnSite_CustIDChanged();
        /// <summary>
        /// There are no comments for Property Global_Org_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Global_Org_Name
        {
            get
            {
                return this._Global_Org_Name;
            }
            set
            {
                this.OnGlobal_Org_NameChanging(value);
                this._Global_Org_Name = value;
                this.OnGlobal_Org_NameChanged();
                this.OnPropertyChanged("Global_Org_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Global_Org_Name;
        partial void OnGlobal_Org_NameChanging(string value);
        partial void OnGlobal_Org_NameChanged();
        /// <summary>
        /// There are no comments for Property Country_Org_Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Country_Org_Name
        {
            get
            {
                return this._Country_Org_Name;
            }
            set
            {
                this.OnCountry_Org_NameChanging(value);
                this._Country_Org_Name = value;
                this.OnCountry_Org_NameChanged();
                this.OnPropertyChanged("Country_Org_Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Country_Org_Name;
        partial void OnCountry_Org_NameChanging(string value);
        partial void OnCountry_Org_NameChanged();
        /// <summary>
        /// There are no comments for Property Site_OrgName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Site_OrgName
        {
            get
            {
                return this._Site_OrgName;
            }
            set
            {
                this.OnSite_OrgNameChanging(value);
                this._Site_OrgName = value;
                this.OnSite_OrgNameChanged();
                this.OnPropertyChanged("Site_OrgName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Site_OrgName;
        partial void OnSite_OrgNameChanging(string value);
        partial void OnSite_OrgNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
